CREATE TABLE organizaciona_jedinica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oj VARCHAR(15) NOT NULL UNIQUE,
    naziv VARCHAR(30) NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    org_unit_id BIGINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_users_org_jedinica
        FOREIGN KEY (org_unit_id) REFERENCES organizaciona_jedinica (id)
);

CREATE UNIQUE INDEX uk_users_username_active
ON users (LOWER(username))
WHERE status = 1;

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);
